"""Product: added count

Revision ID: 24bc20799c55
Revises: 225e9b0a2a93
Create Date: 2025-05-20 03:06:44.884836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24bc20799c55'
down_revision: Union[str, None] = '225e9b0a2a93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('pending', sa.Boolean(), nullable=False))
    op.add_column('product', sa.Column('count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'count')
    op.drop_column('order', 'pending')
    # ### end Alembic commands ###
